### ISSUE TITLE
could you please elaborate the mazes_032_moore_c8.npz file

### ISSUE THREAD

**Issue by qitop** [omron-sinicx/neural-astar#1]
![Untitled](https://user-images.githubusercontent.com/90198160/141495856-23d1b8a8-eafd-47ea-b938-f2734ecc3ca2.png)

I opened the .npz file that is given. 

Can you please tell me what dataset it is and how did you create it?

Also the what are these dimensions that are highlighted. I assume 800 is the training size and 32 * 32 is the size of image that is mentioned in the paper

800 is the input map
800 * 1 is 1 hot matrix representing start position and other 800 * 1 representing the goal position?
What is 800 * 8 * 1 representing?

and the rest 100 represents the validation and test split?

**Comment by yonetaniryo** [comment]
Thank you for the question!

The datafile `mazes_032_moore_c8.npz` was created using our data generation script in a separate repository https://github.com/omron-sinicx/planning-datasets.

`arr_0` - `arr_3` are 800 training, `arr_4` - `arr_7` are 100 validation, and `arr_8` - `arr_11` are 100 test data, which contain the following information (see also https://github.com/omron-sinicx/planning-datasets/blob/68e182801fd8cbc4c25ccdc1b14b8dd99d9bbc73/generate_spp_instances.py#L50-L61):

- `arr_0`, `arr_4`, `arr_8`: binary input maps
- `arr_1`, `arr_5`, `arr_9`: one-hot goal maps
- `arr_2`, `arr_6`, `arr_10`: optimal directions (among eight directions) to reach the goal
- `arr_3`, `arr_7`, `arr_11`: shortest distances to the goal

Note that optimal directions and shortest distances are obtained using the Dijkstra algorithm (see https://github.com/omron-sinicx/planning-datasets/blob/68e182801fd8cbc4c25ccdc1b14b8dd99d9bbc73/planning_datasets_utils/data.py#L155-L159).
