### ISSUE TITLE
question about pq_astar

### ISSUE THREAD

**Issue by HareshKarnan** [omron-sinicx/neural-astar#13]
I was looking at this particular [line](https://github.com/omron-sinicx/neural-astar/blob/6d88e7ca4c00447862da4650e5b339489371e3c4/src/neural_astar/planner/pq_astar.py#L136) and wondering, if there is a bug in this code. Shouldn't we also consider the condition where a node is already in the open list, and maybe has lesser fnew than the one in the open list ?

**Comment by HareshKarnan** [comment]
In that case, open_list needs to be updated with the lower cost fnew

**Comment by yonetaniryo** [comment]
Thank you for raising this issue, and you are right. The cost should be updated also for the nodes that are already in the open list but have higher g value. I was referring to [this implementation](https://rosettacode.org/wiki/A*_search_algorithm#Python) but has somehow misinterpreted it. Will fix it soon!

**Comment by yonetaniryo** [comment]
@HareshKarnan  if you have some time could you please take a look at https://github.com/omron-sinicx/neural-astar/pull/14 to see if the bug about condition is fixed? I'll anyway merge it in this weekend when I have some time.
