### ISSUE TITLE
What's the reason behind using initial obstacles_maps of ones and zeros result in IndexError? 

### ISSUE THREAD

**Issue by cisimon7** [omron-sinicx/neural-astar#20]
Hello, 

I am wondering what it means when the [line](https://github.com/omron-sinicx/neural-astar/blob/6d88e7ca4c00447862da4650e5b339489371e3c4/src/neural_astar/planner/differentiable_astar.py#L123) throws an error message such as: "`IndexError: index -9223372036854775808 is out of bounds for dimension 1 with size 1024`"?

You can get this error for example when running the train.py script and setting `learn_obstacles=True` on [line](https://github.com/omron-sinicx/neural-astar/blob/6d88e7ca4c00447862da4650e5b339489371e3c4/scripts/train.py#L34), and initializing map_obstcles to zeros (`torch.zeros_like(start_maps)`) instead of ones (`torch.ones_like(start_maps)`) on [line](https://github.com/omron-sinicx/neural-astar/blob/6d88e7ca4c00447862da4650e5b339489371e3c4/src/neural_astar/planner/astar.py#L204). Why does initial obstacles_maps of zeros throw an error?

**Comment by yonetaniryo** [comment]
Hi! obstacles_maps take 0 for obstacle regions as used here: https://github.com/omron-sinicx/neural-astar/blob/6d88e7ca4c00447862da4650e5b339489371e3c4/src/neural_astar/planner/differentiable_astar.py#L229

so initializing it to zeros means that all regions are obstacles and there are no feasible paths.

**Comment by cisimon7** [comment]
Thanks for the quick response. I think I got my answer
