### ISSUE TITLE
dataloader for sdd

### ISSUE THREAD

**Issue by zwxu064** [omron-sinicx/neural-astar#23]
Hi, Do you have the dataloader for SDD? For CSM and TiledMP, there are a single .npz for each dataset; but for SDD, there are 8 types each type has some "video" subfolder where each subfolder has several .npz. So I am wondering if you have the dataloader for SDD for reproduce? Thanks.

**Comment by yonetaniryo** [comment]
Hi! Please refer to the icml2021 branch.

https://github.com/omron-sinicx/neural-astar/blob/ff7ef1684facb451662e942aaa4978432a1cbead/planning_experiment/utils/SDD.py#L12


https://github.com/omron-sinicx/neural-astar/blob/ff7ef1684facb451662e942aaa4978432a1cbead/scripts/train_sdd.py#L72

**Comment by zwxu064** [comment]
Thank you very much.
