### ISSUE TITLE
The result of pq_A* and differentiable A* looks same.

### ISSUE THREAD

**Issue by speedhawk** [omron-sinicx/neural-astar#24]
Hi! During running the codes, I advertantly noticed that the contrastical experiments for neural A* is not standard A* but called differentiable A* which is really novel for me. However, after I change it into standard A* (just as the content said, I changed all of `use_differentiable_astar` variable into false), I found that standard A* returned an identical result as differentiable A*. 
I have to say that I am not quite familiar with the algorithm of breadth first searching. Therefore, could you please briefly introduce me about differentiable A* algorithm or recomment me any resource to learn it? Additionally, could you please tell me why the differentiable A* returned the same result as standard A* in these maps? Many thanks and waiting for your reply!

**Comment by yonetaniryo** [comment]
Hi! To get to know neural A\*, you may first check out our blog post:
https://medium.com/sinicx/path-planning-using-neural-a-search-icml-2021-ecc6f2e71b1f

Differentiable A\* indeed returns identical results as those of standard A\*.  It is a re-formulation of A\* to be performed as a part of neural networks.

**Comment by speedhawk** [comment]
> Hi! To get to know neural A*, you may first check out our blog post: https://medium.com/sinicx/path-planning-using-neural-a-search-icml-2021-ecc6f2e71b1f
> 
> Differentiable A* indeed returns identical results as those of standard A*. It is a re-formulation of A* to be performed as a part of neural networks.

Got it! Very thanks for your enlighting and recommending in this field!
