### ISSUE TITLE
Shortest path on a single image

### ISSUE THREAD

**Issue by luizvergennes** [omron-sinicx/neural-astar#26]
Hello, I'm working on your project for an assignment presentation, and I need the shortest path between a start and end position on a map, which would be provided by my user input. My goal is to feed this information into the model to plan the shortest path between these two points. While I’ve made some attempts, I’m not very experienced with Python, so I’m facing some challenges. Would you be able to guide me in the right direction to achieve this?

**Comment by yonetaniryo** [comment]
Thanks for the question! Sorry, but the main maintainer (me) is no longer with this company and cannot accommodate your request. Sorry!
